### ISSUE TITLE
Usage of start attribute

### ISSUE THREAD

**Issue by tmpaul06** [ckeditor/ckeditor5-list#124]
Hi, I am trying to upcast `class` and `start` attributes on a list model. From the source code, I see that there is no explicit model for a `list`, only `listItem`. What is the best way to upcast & downcast using `attributeToAttribute` for an `ol` or `ul` ?

e.g
```html

<ol class="c4" start="2">
   ....

```

I understand that using `start` is not semantically correct, and the list should be a nested child under a larger list. My output is Word > Saved as HTML, and I have to deal with this kind of junk output. I am able to do this for elements like `span` etc by registering them with schema. But for lists, it looks like the model is interwoven with the conversion pipeline.

Edit: In short I am looking for a way to send in `class` and `start` attributes at this line: https://github.com/ckeditor/ckeditor5-list/blob/master/src/converters.js#L796 with my own upcast/downcast converters.

**Comment by Mgsy** [comment]
cc @scofalik

**Comment by scofalik** [comment]
Hi @tmpaul06,

unfortunately, with how the lists are currently represented this is not easy to bring in at the moment. There's no easy way to operate on `<ol>` and `<ul>` attributes. We are aware of that and we don't like it how it is, but we have also other issues to take care of :).

We are planning to work on list types and list start features later this year.

I cannot give you here a whole, working solution because it would be quite time consuming and we have other priorities on our timeline now. It's complex because it involves not only conversion but also behavior when something is done to a list (for example, an item with starting position is outdented/indented). Collaboration also produces some weird cases that we need to cover. This requires introducing additional logic, mostly using post-fixers.

If you can live with imperfect UX (at least until we introduce full support for the feature), I can give you a tip on conversion for `start` attribute. As you noted, there's no model element for `<ul>` or `<ol>`. Instead, you can use the first element of a list as a "representative".

You could write a custom upcast converter for `<li>` which will check if this is the first item in a list if so, check if the list has `start` attribute. You may save it as `listStart` attribute on the model:

```js
editor.conversion.for( 'upcast' ).add( dispatcher => {
    dispatcher.on( 'element:li', ( evt, data, conversionApi ) => {
        // ...
    } );
} );
```

Then, for attribute downcasting, also create your own converter, that will map model item to view item, get the view item's parent (should be `<ul>` or `<ol>`) and set the attribute on that parent:

```js
editor.conversion.for( 'downcast' ).add( dispatcher => {
    dispatcher.on( 'attribute:listStart', ( evt, data, conversionApi ) => {
        // ...
    } );
} );
```

For both converters, you will find tools you need in `data` and `conversionApi` parameters. You can also check existing converters in list plugin to see how they are used.

**Comment by tmpaul06** [comment]
Thanks. Will try to use this approach
