### ISSUE TITLE
Character notation for multilevel numbered lists

### ISSUE THREAD

**Issue by vladikoff** [ckeditor/ckeditor5-list#85]
Character notation for multilevel numbered lists seems to be missing. It would be great to have support for this

From https://github.com/mozilla/notes/issues/413

**[Affected versions]:**
- `    "@ckeditor/ckeditor5-list": "^1.0.0-alpha.2",`

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Numbered list" button, type something and press the "Enter" key.
3. Press the "Tab" key and and observe the list notation.

**[Expected result]:**
- Number "2." modifies into letter "a.".

**[Actual result]:**
- Number "2." modifies into number "1".

**[Notes]:**
- Attached a screen recording of the issue:
![charactr_notation](https://user-images.githubusercontent.com/20083658/33032307-75b50044-ce29-11e7-83de-18179ba46049.gif)

**Comment by scofalik** [comment]
I am not sure how exactly you wish we solve this issue. Do you mean to have it as a configuration option, or do you mean that "by default" it is better to have it like you described?

For us, this is a purely CSS thing connected to looks rather than data. This should be fixed by modifying editor styles (and also, of course, having same styles on the webpage where data will be shown).

If you wish to have a feature that would allow changing list type style while editing, please create a feature request.

**Comment by Reinmar** [comment]
There's a question about the default list feature styles. E.g. image and block quote come with their stylesheets. But I think that in this case we should KISS as the default styles are acceptable (unlike e.g. in bQ case).

**Comment by vladikoff** [comment]
Sounds good 👍  Bug resolution as `wontfix` sounds okay to me. This is mostly a "developer ergonomics" type of issue. Easier to override `ol` style rather than write a bunch of `ol ol ol` selectors for different `list-style-type`s.
